# Generated by Django 3.1.5 on 2021-01-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.BigIntegerField(default='0', verbose_name='phone number'),
        ),
    ]
