# Generated by Django 3.1.1 on 2021-01-14 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[(1, 'MCQ')], default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Quiz name')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date of publication')),
                ('date_active', models.DateTimeField(verbose_name='Date of activation')),
                ('description', models.TextField(blank=True)),
                ('questions', models.ManyToManyField(to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255)),
                ('position', models.IntegerField(verbose_name='position')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='choices', to='quiz.question')),
            ],
            options={
                'unique_together': {('question', 'choice'), ('question', 'position')},
            },
        ),
    ]
