# Generated by Django 3.1.1 on 2021-01-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210114_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='quiz.Question'),
        ),
    ]
