# Generated by Django 3.1.1 on 2021-01-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210114_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[(1, 'MCQ')], max_length=100),
        ),
    ]
