# Generated by Django 3.1.1 on 2021-01-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210114_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'MCQ')], default=1),
        ),
    ]
