# Generated by Django 3.1.1 on 2021-01-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210114_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='choices', to='quiz.MultipleChoiceAnswer'),
        ),
        migrations.AlterUniqueTogether(
            name='multiplechoiceanswer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='position',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='question',
        ),
    ]
