# Generated by Django 3.1.5 on 2021-01-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date_active',
            field=models.DateField(verbose_name='Date of activation'),
        ),
    ]
