# Generated by Django 3.1.5 on 2021-01-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quiz_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizinstance',
            name='curr_question',
            field=models.IntegerField(default=1, verbose_name='Currently on question number'),
        ),
    ]
