# Generated by Django 3.1.5 on 2021-01-16 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0013_auto_20210115_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizinstance',
            name='taker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taker', to=settings.AUTH_USER_MODEL),
        ),
    ]
